//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    
    public partial class ProductoGetById_Result1
    {
        public int IdProducto { get; set; }
        public string NombreProducto { get; set; }
        public string Descripcion { get; set; }
        public string PaisOrigen { get; set; }
        public decimal Precio { get; set; }
        public int IdSubCategori { get; set; }
        public string Imagen { get; set; }
        public Nullable<int> Stock { get; set; }
        public int IdCategoria { get; set; }
    }
}
